name: Scraper Combustibles

on:
  schedule:
    - cron: "0 6 1,16 * *" # d√≠a 1 y 16 de cada mes a las 06:00 UTC
  workflow_dispatch:

jobs:
  combustibles:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper combustibles
        run: |
          python scrapers/scraper_combustibles.py

      - name: Commit data
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/combustibles
          git commit -m "chore: update combustibles" || echo "No changes"
          git push
