name: Scraper IPC

permissions:
  contents: write

on:
  schedule:
    - cron: "0 5 10 * *"
    - cron: "0 5 11 * *"
    - cron: "0 5 12 * *"
    - cron: "0 5 13 * *"
    - cron: "0 5 14 * *"
  workflow_dispatch:

jobs:
  ipc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper IPC
        run: |
          python scrapers/scraper_ipc.py

      - name: Commit data
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/ipc
          git commit -m "chore: update IPC" || echo "No changes"
          git push
